name: meyn_lbh_simulation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  #  sdk: '>=3.1.1 <4.0.0'
  # sdk: '>=3.5.0-180.3.beta <4.0.0'
  sdk: '>=3.4.4'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  get_it: ^7.7.0
  url_launcher: ^6.3.0
  user_command: ^0.0.8
  fling_units: ^2.2.7
  process_run: ^0.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  given_when_then_unit_test: ^0.2.1
  shouldly: ^0.5.0+1
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/meyn.ico"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/meyn.ico"
  windows:
    generate: true
    image_path: "assets/icon/meyn.ico"
    icon_size: 48 # min:48, max:256, default: 48



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
