name: meyn_lbh_simulation
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  #  sdk: '>=3.1.1 <4.0.0'
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  get_it: ^7.7.0
  url_launcher: ^6.3.0
  user_command: ^0.0.8
  fling_units: ^2.2.7
  process_run: ^0.14.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  given_when_then_unit_test: ^0.2.1
  shouldly: ^0.5.0+1
  flutter_lints: ^4.0.0




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
