name: meyn_lbh_simulation
description: Meyn live bird handling simulation

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <=3.0.1"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  get_it: ^7.2.0
  url_launcher: ^6.1.2
  process_run: ^0.12.3+2
  user_command: ^0.0.4
  fling_units: ^2.0.2


dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
